default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample2_development

test:
  <<: *default
  database: sample2_test


production:
  <<: *default
  database: sample2_production
  username: sample2
  password: <%= ENV['SAMPLE2_DATABASE_PASSWORD'] %>
